### ISSUE TITLE
Accessing the program from command line interface dosent work.

### ISSUE THREAD

**Issue by kshitijzutshi** [alimasri/movies_organizer#1]
__C:\Users\abc>movies_organizer --src K:\MOVIE --dst K:\movies_organizer --auto
'movies_organizer' is not recognized as an internal or external command,
operable program or batch file.__

**Comment by alimasri** [comment]
This message means that the software is not installed/accessible from your command line. Please verify that the software is correctly installed. For more information follow the installation directions in the README file.
